apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: minicms
spec:
  selector:
    matchLabels:
      app: minicms
  template:
    metadata:
      labels:
        app: minicms
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - mountPath: "/data/mongo"
            subPath: "minicms-mongo"
            name: minicms-mongo-store
      - name: simple-rest
        image: simple-rest:1.0.0
        ports:
        - containerPort: 9090
        imagePullPolicy: Never
