apiVersion: v1
kind: PersistentVolume
metadata:
  name: minicms-storage
  labels:
    qtree: minicms
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minicms-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests: 
      storage: 5Gi
  selector:
    matchLabels:
      qtree: minicms
